# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_mainWindow(object):
    def setupUi(self, Dialog_mainWindow):
        Dialog_mainWindow.setObjectName("Dialog_mainWindow")
        Dialog_mainWindow.resize(356, 195)

        self.buttonBox_startProject = QtWidgets.QDialogButtonBox(Dialog_mainWindow)
        self.buttonBox_startProject.setGeometry(QtCore.QRect(180, 150, 161, 32))
        self.buttonBox_startProject.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_startProject.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_startProject.setObjectName("buttonBox_startProject")

        self.label_mainTitle = QtWidgets.QLabel(Dialog_mainWindow)
        self.label_mainTitle.setGeometry(QtCore.QRect(120, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_mainTitle.setFont(font)
        self.label_mainTitle.setObjectName("label_mainTitle")

        self.label_nombreDelProyecto = QtWidgets.QLabel(Dialog_mainWindow)
        self.label_nombreDelProyecto.setGeometry(QtCore.QRect(20, 120, 121, 16))
        self.label_nombreDelProyecto.setObjectName("label_nombreDelProyecto")

        self.checkBox_localRepo = QtWidgets.QCheckBox(Dialog_mainWindow)
        self.checkBox_localRepo.setGeometry(QtCore.QRect(20, 50, 151, 17))
        self.checkBox_localRepo.setObjectName("checkBox_localRepo")

        self.lineEdit_projectName = QtWidgets.QLineEdit(Dialog_mainWindow)
        self.lineEdit_projectName.setGeometry(QtCore.QRect(150, 120, 191, 20))
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")

        self.checkBox_remoteRepo = QtWidgets.QCheckBox(Dialog_mainWindow)
        self.checkBox_remoteRepo.setGeometry(QtCore.QRect(20, 70, 161, 17))
        self.checkBox_remoteRepo.setObjectName("checkBox_remoteRepo")
        
        self.checkBox_virtualEnv = QtWidgets.QCheckBox(Dialog_mainWindow)
        self.checkBox_virtualEnv.setGeometry(QtCore.QRect(20, 90, 191, 17))
        self.checkBox_virtualEnv.setObjectName("checkBox_virtualEnv")

        self.retranslateUi(Dialog_mainWindow)
        QtCore.QMetaObject.connectSlotsByName(Dialog_mainWindow)

    def retranslateUi(self, Dialog_mainWindow):
        _translate = QtCore.QCoreApplication.translate
        Dialog_mainWindow.setWindowTitle(_translate("Dialog_mainWindow", "CREADOR DE PROYECTOS EN GIT"))
        self.label_mainTitle.setText(_translate("Dialog_mainWindow", "Crear Proyecto"))
        self.label_nombreDelProyecto.setText(_translate("Dialog_mainWindow", "Nombre del Proyecto:"))
        self.checkBox_localRepo.setText(_translate("Dialog_mainWindow", "Crear Repositorio Local"))
        self.checkBox_remoteRepo.setText(_translate("Dialog_mainWindow", "Crear Repositorio Remoto"))
        self.checkBox_virtualEnv.setText(_translate("Dialog_mainWindow", "Crear Entorno Virtual de Python 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_mainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog_mainWindow()
    ui.setupUi(Dialog_mainWindow)
    Dialog_mainWindow.show()
    sys.exit(app.exec_())
